### ISSUE TITLE
calibre can not load some book gen by mobi

### ISSUE THREAD

**Issue by ystyle** [leotaku/mobi#1]
```shell
calibre, version 5.0.1
错误： 无法加载书籍: 无法打开位于 E:\Kindle\电子书\第九特区\第九特区.azw3 的书籍，点击“查看详情”获取更多信息。

Failed to convert book: E:\Kindle\电子书\第九特区\第九特区.azw3 with **error:**
InputFormatPlugin: MOBI Input running
on E:\Kindle\电子书\第九特区\第九特区.azw3
Found KF8 MOBI of type 'standalone'
Failed to run pipe worker with command: from calibre.srv.render_book import viewer_main; viewer_main()
Traceback (most recent call last):
  File "runpy.py", line 194, in _run_module_as_main
  File "runpy.py", line 87, in _run_code
  File "site.py", line 89, in <module>
  File "site.py", line 84, in main
  File "site.py", line 55, in run_entry_point
  File "site-packages\calibre\utils\ipc\worker.py", line 195, in main
  File "<string>", line 1, in <module>
  File "site-packages\calibre\srv\render_book.py", line 871, in viewer_main
  File "site-packages\calibre\srv\render_book.py", line 862, in render_for_viewer
  File "site-packages\calibre\srv\render_book.py", line 839, in render
  File "site-packages\calibre\ebooks\oeb\iterator\book.py", line 63, in extract_book
  File "site-packages\calibre\customize\conversion.py", line 245, in __call__
  File "site-packages\calibre\ebooks\conversion\plugins\mobi_input.py", line 47, in convert
  File "site-packages\calibre\ebooks\mobi\reader\mobi8.py", line 109, in __call__
  File "site-packages\calibre\ebooks\mobi\reader\mobi8.py", line 131, in read_indices
  File "site-packages\calibre\ebooks\mobi\reader\index.py", line 275, in read_index
  File "site-packages\calibre\ebooks\mobi\reader\index.py", line 241, in parse_index_record
  File "site-packages\calibre\ebooks\mobi\utils.py", line 42, in decode_string
struct.error: unpack requires a buffer of 1 bytes
```

[kaf-cli](https://github.com/ystyle/kaf-cli) ： A tool I made to convert txt novels to azw3 format

the book of txt: 
[《第九特区》（校对版全本）作者：伪戒.txt](https://github.com/leotaku/mobi/files/7740815/default.txt)

kaf-cli command： 
```shell
kaf-cli.exe -filename .\《第九特区》（校对版全本）作者：伪戒.txt -bookname 第九特区 -author 伪戒
```

    The converted azw3 cannot be opened on calibre and Kindle Oasis3, but the pc version of the kindle reader can be opened

**Comment by leotaku** [comment]
On first glance, this looks like a bug with my implementation of generating the INDX buffer. The code in question is basically entirely reverse-engineered, so it is probably not that robust.

I see the file you have provided contains mostly Chinese characters which of course span multiple unicode bytes. (As someone who only knows languages using the Latin script, I have not extensively tested my library under these conditions) The file is also very large. I expect that one of these factors, or a combination, is the reason for the bug.

Unfortunately, I have an important exam coming up, so I will only be able to look into this later this week. In the meantime, I would appreciate if you could also provide the generated AZW3 file in addition to the text source.

Thanks

**Comment by leotaku** [comment]
On second thought, please also try converting your source text file to from [CP936](https://en.wikipedia.org/wiki/Code_page_936_(Microsoft_Windows)) to UTF8 encoding before converting it to AZW3 and see if that fixes the issue.

```sh
# The following command should achieve this task
iconv -f cp936 -t utf-8 input.txt > output.txt
```

**Comment by ystyle** [comment]
> On first glance, this looks like a bug with my implementation of generating the INDX record. The code in question is basically entirely reverse-engineered, so it is probably not that robust.
> 
> I see the file you have provided contains mostly Chinese characters which of course span multiple unicode bytes. (As someone who only knows languages using the Latin script, I have not extensively tested my library under these conditions) The file is also very large. I expect that one of these factors, or a combination, is the reason for the bug.
> 
> Unfortunately, I have an important exam coming up, so I will only be able to look into this later this week. In the meantime, I would appreciate if you could also provide the generated AZW3 file in addition to the text source.
> 
> Thanks

the azw3 file:  [第九特区.zip](https://github.com/leotaku/mobi/files/7744958/default.zip)

kaf-cli has converted the character set to utf8 , and the conversion does not often encounter the failure of the conversion of azw3

ps: It’s not in a hurry, you can do it whenever you have time.

**Comment by leotaku** [comment]
I've looked into this now and this seems to be caused by a limitation of the MOBI/AZW3 format, rather than by a bug in my library. You see, with MOBI, certain offsets into index records are stored as [16-bit integers](https://github.com/leotaku/mobi/blob/a9633174585442ab0b64a313d0fdb5397260a722/records/indx.go#L44). The book you are trying to generate is large enough to causes a 16-bit integer overflow and thus break the generated chunk index.

Unfortunately, I don't think there is anything I can do to fix this. There just seems to be a hard limit on the amount of chunks, and by extension chapters, a MOBI-formatted book can have.

**Comment by ystyle** [comment]
Does it mean the number of chapters?

**Comment by leotaku** [comment]
Yes and no. 

What is actually overflowing are the indexes into the Skeleton IDXT record, which is chunk based, because its entries are significantly longer than the ones of the NCX IDXT record, which is chapter based. 

It would technically be possible to squeeze out a bit more by adding a skeleton/chunk "optimizer" to the library, but I don't really think that this would be worth justifying the additional complexity, especially because, if you needed to generate a book with a few more chapters, the offsets into the NCX IDXT record, where no additional optimization is possible, would likely also overflow.

From what I can see, the book you are trying to generate would have *2854* individual chapters, correct? I personally have never seen an e-book with this many chapters, so it wouldn't surprise me if we are really just past the limit of what is possible with the MOBI format here.

**Comment by ystyle** [comment]
Use calibre to transfer an azw3 file that can be opened normally：
[default - Wei Zhi.zip](https://github.com/leotaku/mobi/files/7779744/default.-.Wei.Zhi.zip)

**Comment by leotaku** [comment]
I'm not sure what you are trying to tell me in your last comment?

**Comment by ystyle** [comment]
My problem has been solved. When kaf-cli converts azw3 format, a file is generated every 2000 chapters.

The above file is what I want to try to see if the file converted by calibre is correct, and it can be opened normally after being transferred. If you are interested, you can take a look at the difference between the two.

Finally, thank you for your answers.

**Comment by leotaku** [comment]
Thank you for the calibre-generated file! With it, I have been able to find a significant bottleneck in my library. 

Previously, I used to store [some redundant data](https://github.com/leotaku/mobi/blob/86660dc4ab9be107304ac0395d55c8a6ab1fe059/records/index.go#L98-L99) in my Skeleton IDXT entries. I used to think this was required by the spec, but I can no longer find any indication of that, so it most likely was a misunderstanding on my part. In any case, this information is seemingly ignored by all MOBI readers I have tested. Removing it reduces the average size of a Skeleton IDXT record for e-books of larger sizes from **30** bytes to just **23** and in turn should increase the number of possible chunks and chapters from around **2100** to around **2800** (these are very rough estimates).

I think your fix of generating new files whenever a certain threshold of chapters is reached is the only general solution to this problem, but with the newest version of my library, you should be able to tune that threshold up to at least 2500 chapters and higher without running into any errors.
